"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
var express_1 = require("express");
var customer_1 = require("./customer");
var course_1 = require("./course");
var author_1 = require("./author");
var category_1 = require("./category");
var rentals_1 = require("./rentals");
var user_1 = require("./user");
var router = express_1.default.Router();
router.use(customer_1.customerRouter);
router.use(course_1.coursesRouter);
router.use(author_1.authorsRouter);
router.use(category_1.categoryRouter);
router.use(rentals_1.rentalsRouter);
router.use(user_1.usersRouter);
exports.default = router;
